### ISSUE TITLE
Two mains

### ISSUE THREAD

**Issue by logan-yliniemi** [Jeremy-Fries/MAP-Elites-v1#1]
@Jeremy-Fries : Why are there two main folders? It appears that we're syncing a subfolder we don't need.

**Comment by logan-yliniemi** [comment]
@sierrasaurous : Please include the up-to-date CL/CD file, even if we have to relocate it to where the executable is built.

**Comment by logan-yliniemi** [comment]
@sierrasaurous @Jeremy-Fries @sforer580 : This currently throws a linker error for me with lots of duplicated objects; any insight on where this will be from?

**Comment by Jeremy-Fries** [comment]
I'll take a look at it in a few. I removed the second main file last night
but may not have pushed it.

-Jeremy

**Comment by Jeremy-Fries** [comment]
Deleted empty main file.

**Comment by logan-yliniemi** [comment]
Push changes and close issue.
