### ISSUE TITLE
Linker Errors

### ISSUE THREAD

**Issue by logan-yliniemi** [Jeremy-Fries/MAP-Elites-v1#3]
@sierrasaurous @Jeremy-Fries @sforer580 : This currently throws a linker error for me with lots of duplicated objects; any insight on where this will be from?

**Comment by Jeremy-Fries** [comment]
I'm taking a look at it.

**Comment by Jeremy-Fries** [comment]
Found where the issue is stemming from. Looks to be the #include "Simulator.hpp". Had the same error when bringing it up to main.

**Comment by logan-yliniemi** [comment]
If it is easily fixable, please do so and push changes.

**Comment by Jeremy-Fries** [comment]
Narrowed it down to when this is called in the simulator.hpp and as well in dynamics.h:
#include "anglemath.h".

**Comment by Jeremy-Fries** [comment]
When anglemath.h or dynamics.h are called from anywhere besides the main, throws the error.

**Comment by logan-yliniemi** [comment]
It's an order-of-inclusion error; it's possible that we have circular inclusions because of the integration process. If that's the case we have a bigger problem, but it might not be.

Can we load them earlier in the order of inclusions?

**Comment by Jeremy-Fries** [comment]
At the moment I am not sure. I will take a look at it though.

**Comment by logan-yliniemi** [comment]
Linker Fixes allows the files to compile together.
